name: Hellos
on: push
defaults:
  run:
    shell: pwsh
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set output variable
        #shell: bash
        run: |
          echo ${{ github.workspace }}/abc.txt
          $value=cat ${{ github.workspace }}/abc.txt
          echo $value
          echo foo=bar >> $GITHUB_OUTPUT
      - name: Set enviornment variable
        run: |
          echo foo=bar >> $env:GITHUB_OUTPUT
      - name: Set values step one
        id: set_one
        run: |
          echo "action_state=yellow" >> "GITHUB_ENV"   
      - name: Set values step two
        id: set_two
        run: |
          echo "${{ env.action_state }}"
